In [1]:
import torch

In [2]:
from __future__ import print_function

In [3]:
x = torch.empty(5, 3)
x

tensor([[3.4190e-04, 6.2078e-43, 3.4190e-04],
        [6.2078e-43, 3.4194e-04, 6.2078e-43],
        [3.4187e-04, 6.2078e-43, 3.4187e-04],
        [6.2078e-43, 3.4187e-04, 6.2078e-43],
        [3.4187e-04, 6.2078e-43, 3.4187e-04]])

In [4]:
x = torch.rand(5, 3)
x

tensor([[0.1242, 0.4447, 0.5281],
        [0.2645, 0.2881, 0.8841],
        [0.3628, 0.7452, 0.4443],
        [0.1453, 0.4905, 0.8098],
        [0.0070, 0.2702, 0.3363]])

In [5]:
x[0]

tensor([0.1242, 0.4447, 0.5281])

In [6]:
# construct a matrix filled zeros and of dtype long:

x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [7]:
# Construct a tensor directly from data:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [8]:
# or create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.8591,  1.9521, -0.3260],
        [ 1.3387,  0.8397, -0.3712],
        [-0.2785, -0.1250,  0.2445],
        [-0.6902, -0.5450, -0.6942],
        [ 0.3411, -0.3899, -1.1654]])


In [9]:
print(x.size())

torch.Size([5, 3])


In [10]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.3883,  2.1014,  0.2480],
        [ 2.1686,  1.8072, -0.2582],
        [ 0.2174,  0.3891,  1.1384],
        [-0.1528,  0.3939, -0.5521],
        [ 1.2389, -0.1536, -0.4104]])


In [11]:
print(x)
print(y)

tensor([[-0.8591,  1.9521, -0.3260],
        [ 1.3387,  0.8397, -0.3712],
        [-0.2785, -0.1250,  0.2445],
        [-0.6902, -0.5450, -0.6942],
        [ 0.3411, -0.3899, -1.1654]])
tensor([[0.4707, 0.1492, 0.5740],
        [0.8298, 0.9675, 0.1130],
        [0.4959, 0.5141, 0.8939],
        [0.5374, 0.9389, 0.1421],
        [0.8978, 0.2363, 0.7550]])


In [12]:
x + y

tensor([[-0.3883,  2.1014,  0.2480],
        [ 2.1686,  1.8072, -0.2582],
        [ 0.2174,  0.3891,  1.1384],
        [-0.1528,  0.3939, -0.5521],
        [ 1.2389, -0.1536, -0.4104]])

In [13]:
print(torch.add(x, y))

tensor([[-0.3883,  2.1014,  0.2480],
        [ 2.1686,  1.8072, -0.2582],
        [ 0.2174,  0.3891,  1.1384],
        [-0.1528,  0.3939, -0.5521],
        [ 1.2389, -0.1536, -0.4104]])


In [14]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.3883,  2.1014,  0.2480],
        [ 2.1686,  1.8072, -0.2582],
        [ 0.2174,  0.3891,  1.1384],
        [-0.1528,  0.3939, -0.5521],
        [ 1.2389, -0.1536, -0.4104]])


In [15]:
y.add_(x)
print(y)

tensor([[-0.3883,  2.1014,  0.2480],
        [ 2.1686,  1.8072, -0.2582],
        [ 0.2174,  0.3891,  1.1384],
        [-0.1528,  0.3939, -0.5521],
        [ 1.2389, -0.1536, -0.4104]])


In [16]:
# You can use standard NumPy-like indexing with all bells and whistles!
print(x[:, 1])

tensor([ 1.9521,  0.8397, -0.1250, -0.5450, -0.3899])


In [17]:
# Resizing: If you want to resize/reshape tensor, you can use torch.view:

x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [18]:
# If you have a one element tensor, use .item() to get the value as a Python number

x = torch.randn(1)
print(x)
print(x.item())

tensor([1.0060])
1.006004810333252


# Converting a Torch Tensor to a NumPy Array

In [19]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [20]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [21]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


# Converting NumPy Array to Torch Tensor

## See how changing the np array changed the Torch Tensor automatically

In [22]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# CUDA Tensors

## Tensors can be moved onto any device using the .to method.

In [23]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.one_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))
else:
    print(y.add_(x))

tensor([ 1.4748,  0.2941, -0.7140,  1.3537,  1.5393,  1.0583,  2.9887,  1.0368,
         1.0210,  3.0523,  2.3477,  0.4403,  1.1480,  2.4508,  0.0388,  3.3158])


# Autograd: Automatic Differentiation

In [24]:
import torch

In [25]:
x = torch.ones(2, 3, requires_grad=True)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [26]:
y = x + 2
print(y)

tensor([[3., 3., 3.],
        [3., 3., 3.]], grad_fn=<AddBackward0>)


In [27]:
print(y.grad_fn)

In [28]:
z = y*y*3
out = z.mean()
print(z, out)

tensor([[27., 27., 27.],
        [27., 27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [29]:
a = torch.randn(2, 2)
a = ((a*3)/(a-1))
print(a.requires_grad)

False


In [30]:
a.requires_grad_(True)
print(a.requires_grad)

True


In [31]:
b = (a*a).sum()
print(b.grad_fn)

In [32]:
out

tensor(27., grad_fn=<MeanBackward0>)

In [33]:
out.backward()

In [35]:
print(x.grad)

None


In [36]:
x = torch.randn(3, requires_grad=True)
y = x * 2
print(y.data.norm())
while y.data.norm() < 1000:
    y = y*2
print(y)

tensor(2.1771)
tensor([  165.6781, -1099.2965,    81.0477], grad_fn=<MulBackward0>)


In [37]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [38]:
print(x.requires_grad)

True


In [39]:
print((x**2).requires_grad)

True


In [40]:
with torch.no_grad():
    print((x**2).requires_grad)

False


In [41]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)
